spring.application.name=sistema-usuario

# ==============================================================
# CONFIGURACIÓN DE DATOS Y ORM (Capa de Infraestructura)
# ==============================================================
spring.datasource.url=jdbc:mysql://localhost:3306/sistema_usuarios?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate ddl-auto=update: Spring creará o actualizará las tablas en base a nuestras clases Modelo.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
