spring.application.name=colegio

spring.datasource.url=jdbc:mysql://localhost:3306/colegio?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
# Dejamos la contraseña en blanco por defecto, tal como lo prefieres para tus entornos locales
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 3. Configuración de JPA e Hibernate (El ORM)
# 'update' permite que Spring Boot lea tus clases @Entity y cree las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
# Muestra las sentencias SQL en la consola para facilitar la depuración
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pruebamailsender011@gmail.com
spring.mail.password=rpft yzzm pbxv mliw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true